//Global famous component
Surface         = require('famous/core/Surface');
Engine          = require('famous/core/Engine');
View            = require('famous/core/View');
Transform       = require('famous/core/Transform');
StateModifier   = require('famous/modifiers/StateModifier');
HeaderFooter    = require('famous/views/HeaderFooterLayout');
ImageSurface    = require('famous/surfaces/ImageSurface');
FastClick       = require('famous/inputs/FastClick');